-- ONE-NET | Vendor POS (Seller custody + settlement)
-- شغّل هذا الملف في Supabase SQL Editor مرة واحدة

-- 1) إضافة seller_user_id إلى invoices (لربط الفاتورة بالبائع)
alter table if exists public.invoices
  add column if not exists seller_user_id uuid;

create index if not exists idx_invoices_seller_user_id on public.invoices(seller_user_id);

-- 2) جدول عهدة البائع
create table if not exists public.vendor_stock (
  seller_user_id uuid not null,
  card_type_id bigint not null,
  card_name text null,
  qty numeric not null default 0,
  updated_at timestamptz not null default now(),
  primary key (seller_user_id, card_type_id)
);

-- سجل حركة العهدة
create table if not exists public.vendor_stock_movements (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  actor_id uuid null,
  seller_user_id uuid not null,
  card_type_id bigint not null,
  movement_type text not null check (movement_type in ('IN','OUT')),
  qty numeric not null check (qty > 0),
  note text null
);

create index if not exists idx_vendor_stock_mov_seller on public.vendor_stock_movements(seller_user_id, created_at desc);

-- 3) جدول تسليم الكاش من البائع للإدارة (للتسوية)
create table if not exists public.seller_deposits (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  actor_id uuid null,
  seller_user_id uuid not null,
  deposit_date date not null default (now()::date),
  amount numeric not null check (amount > 0),
  note text null
);

create index if not exists idx_seller_deposits_seller_date on public.seller_deposits(seller_user_id, deposit_date desc);

-- 4) دالة تحديث عهدة البائع (خصم/إضافة) مع تحقق من الرصيد
-- ملاحظة: نظامنا لا يستخدم Supabase Auth، لذلك نتحقق عبر app_users + actor_id المرسل من الواجهة.
create or replace function public.vendor_stock_move(
  p_actor_id uuid,
  p_seller_user_id uuid,
  p_card_type_id bigint,
  p_movement_type text,
  p_qty numeric,
  p_note text default null,
  p_created_at timestamptz default null
)
returns void
language plpgsql
security definer
as $$
declare
  v_actor_role text;
  v_is_active boolean;
  v_qty numeric;
  v_now timestamptz := coalesce(p_created_at, now());
begin
  if p_seller_user_id is null then
    raise exception 'seller_user_id required';
  end if;
  if p_card_type_id is null then
    raise exception 'card_type_id required';
  end if;
  if p_qty is null or p_qty <= 0 then
    raise exception 'qty must be > 0';
  end if;

  select u.role, u.is_active into v_actor_role, v_is_active
  from public.app_users u
  where u.id = p_actor_id;

  if v_actor_role is null or v_is_active is distinct from true then
    raise exception 'actor not allowed';
  end if;

  -- السماح: البائع يخصم/يرجع من عهدته فقط، والإدارة (super_admin/manager) تقدر تعمل للجميع
  if (lower(v_actor_role) = 'seller') then
    if p_actor_id <> p_seller_user_id then
      raise exception 'seller can operate only on own custody';
    end if;
  elsif (lower(v_actor_role) in ('super_admin','manager')) then
    -- ok
  else
    raise exception 'role not allowed';
  end if;

  -- upsert row
  insert into public.vendor_stock (seller_user_id, card_type_id, qty, updated_at)
  values (p_seller_user_id, p_card_type_id, 0, v_now)
  on conflict (seller_user_id, card_type_id)
  do update set updated_at = excluded.updated_at;

  select qty into v_qty
  from public.vendor_stock
  where seller_user_id = p_seller_user_id and card_type_id = p_card_type_id
  for update;

  if upper(p_movement_type) = 'OUT' then
    if v_qty < p_qty then
      raise exception 'INSUFFICIENT_VENDOR_STOCK';
    end if;
    update public.vendor_stock
      set qty = qty - p_qty,
          updated_at = v_now
      where seller_user_id = p_seller_user_id and card_type_id = p_card_type_id;
  elsif upper(p_movement_type) = 'IN' then
    update public.vendor_stock
      set qty = qty + p_qty,
          updated_at = v_now
      where seller_user_id = p_seller_user_id and card_type_id = p_card_type_id;
  else
    raise exception 'movement_type must be IN or OUT';
  end if;

  insert into public.vendor_stock_movements(created_at, actor_id, seller_user_id, card_type_id, movement_type, qty, note)
  values (v_now, p_actor_id, p_seller_user_id, p_card_type_id, upper(p_movement_type), p_qty, p_note);

end;
$$;

-- 5) دالة تسجيل إيداع (تسليم الكاش) - للإدارة فقط
create or replace function public.seller_deposit_add(
  p_actor_id uuid,
  p_seller_user_id uuid,
  p_deposit_date date,
  p_amount numeric,
  p_note text default null
)
returns void
language plpgsql
security definer
as $$
declare
  v_actor_role text;
  v_is_active boolean;
begin
  select u.role, u.is_active into v_actor_role, v_is_active
  from public.app_users u
  where u.id = p_actor_id;

  if v_actor_role is null or v_is_active is distinct from true then
    raise exception 'actor not allowed';
  end if;

  if lower(v_actor_role) not in ('super_admin','manager') then
    raise exception 'only admin/manager can add deposit';
  end if;

  insert into public.seller_deposits(actor_id, seller_user_id, deposit_date, amount, note)
  values (p_actor_id, p_seller_user_id, coalesce(p_deposit_date, now()::date), p_amount, p_note);
end;
$$;

-- 6) (اختياري) مزامنة اسم الصنف داخل vendor_stock من card_types
-- يمكنك تشغيله مرة واحدة بعد إنشاء العهدة
update public.vendor_stock vs
set card_name = ct.name
from public.card_types ct
where vs.card_type_id = ct.id
  and (vs.card_name is null or vs.card_name = '');
